# The Configuration File for the FireworkJoin Plugin
# Firework types: BALL, BALL_LARGE, BURST, CREEPER, STAR
delay: 1
fireworks:
  - type: STAR
    power: 0
    colors:
      - red: 255
        green: 0
        blue: 0
  - type: BALL
    power: 0
    colors:
      - red: 0
        green: 255
        blue: 0